version: 2

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
release:
  github:
  name_template: "{{.Version}}"
  prerelease: auto
  mode: append
changelog:
  disable: true
