FROM debian:bookworm
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends systemd && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
COPY entrypoint.sh /
ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
